"""empty message

Revision ID: 23ee20997ef0
Revises: 1fbb68c02e29
Create Date: 2025-09-06 01:09:43.086348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23ee20997ef0'
down_revision = '1fbb68c02e29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association_routines',
    sa.Column('routines_id', sa.Integer(), nullable=True),
    sa.Column('workout_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['routines_id'], ['routines.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], )
    )
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.drop_constraint('workout_rutinas_id_fkey', type_='foreignkey')
        batch_op.drop_column('rutinas_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rutinas_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('workout_rutinas_id_fkey', 'routines', ['rutinas_id'], ['id'])

    op.drop_table('association_routines')
    # ### end Alembic commands ###
