"""empty message

Revision ID: a55039d0ff1c
Revises: 6d399a00fd46
Create Date: 2025-08-25 04:46:58.205633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a55039d0ff1c'
down_revision = '6d399a00fd46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=15), nullable=False))
        batch_op.drop_column('is_trainer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_trainer', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('role')

    # ### end Alembic commands ###
